### ISSUE TITLE
 File format unknown. Impossible to import file.

### ISSUE THREAD

**Issue by FabianCernota** [eshiol/plg_j2xml_importer15#1]
Hey hey,
i want to migrate my old Joomla 1.5 instance. I install the development build in Joomla 3.4 and export the structure in Joomla 1.5, this works also importing the users. Now i want to import the first block but i get the error 
File format unknown. Impossible to import file.
- Fabian

**Comment by eshiol** [comment]
You probably tried to upload too large file. Please, try exporting articles without images. You can copy them in a second time via ftp.

**Comment by FabianCernota** [comment]
Oh the good old max upload size :D Where is the folder which i need to upload?

**Comment by eshiol** [comment]
You can't upload a file manually. So you need to reduce the file size by disabling the image export or decreasing the block size.
![com_j2xml15_7](https://cloud.githubusercontent.com/assets/12718836/8002938/fbebbda0-0b72-11e5-83ef-f0ee601edfc5.png)
